version: "3.3"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:44"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.resolvers=1.1.1.1:53"
      - "--certificatesresolvers.myresolver.acme.email=dawdwa@dawdwa.de"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--accesslog=true"
      - "--accesslog.format=json"
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
      - "./static:/static" # static files
    environment:
      - CF_DNS_API_TOKEN=qNaX16lSKBEFuBZMJpi_nKc9Hju9kkOddGbhocXm
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.robots.rule=Path(`/static/robots.txt`)"
      - "traefik.http.routers.robots.entrypoints=websecure"
      - "traefik.http.routers.robots.service=static"
      - "traefik.http.services.static.loadbalancer.server.root=/static"
      - "traefik.http.routers.api.middlewares=traefik-logger"
      - "traefik.middleware.traefik-logger.accesslog=true"
    restart: unless-stopped
    networks:
      - main-network

  n8n:
    image: n8nio/n8n
    container_name: n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=zX57Lp92CqFmT8rL
      - N8N_SECURE_COOKIE=true
      - WEBHOOK_URL=https://workflow.newflow.io
      - N8N_LOG_LEVEL=debug
      - N8N_LOG_OUTPUT=console
      - N8N_DIAGNOSTICS_ENABLED=false
      - TZ=Europe/Berlin
      - GENERIC_TIMEZONE=Europe/Berlin
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      - N8N_FOLDERS_ENABLED=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`workflow.newflow.io`)"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls.certresolver=myresolver"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - "traefik.http.routers.n8n-web.rule=Host(`workflow.newflow.io`)"
      - "traefik.http.routers.n8n-web.entrypoints=web"
      - "traefik.http.routers.n8n-web.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    networks:
      - main-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6334:6333"   # Expose Qdrant's internal port 6333 on host port 6334 (if needed)
    restart: unless-stopped
    networks:
      - main-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "6333:80"     # Expose nginx port 80 on host port 6333
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    networks:
      - main-network

volumes:
  n8n_data:
    driver: local

networks:
  main-network:
    driver: bridge