version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_SECURE_COOKIE=${N8N_SECURE_COOKIE:-false}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_LOG_LEVEL=info
      - N8N_LOG_OUTPUT=console
      - N8N_DIAGNOSTICS_ENABLED=false
      - TZ=Europe/Berlin
      - GENERIC_TIMEZONE=Europe/Berlin
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=${N8N_COMMUNITY_PACKAGES:-true}
      - N8N_FOLDERS_ENABLED=${N8N_FOLDERS_ENABLED:-true}
      # Database configuration (will be overridden if PostgreSQL is used)
      - DB_TYPE=${N8N_DATABASE_TYPE:-sqlite}
      - DB_SQLITE_DATABASE=/home/node/.n8n/database.sqlite
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    networks:
      - n8n-network

volumes:
  n8n_data:
    driver: local

networks:
  n8n-network:
    driver: bridge 